# **SURUTHI S**
# 225229141

# Lab2. Red Wine Quality Data Analysis using NumPy Part-II

In [1]:
import numpy as np

In [2]:
from numpy import genfromtxt
wines = genfromtxt('winequality-red.csv', delimiter=',', skip_header = 1)
print(wines)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [3]:
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

**Find sum of all residual sugar values**

In [4]:
wines.sum(axis=0)[3]

4059.550000000003

**Find sums of every feature value. There are 12 features altogether**

In [5]:
wines.sum(axis =0 )

array([13303.1    ,   843.985  ,   433.29   ,  4059.55   ,   139.859  ,
       25384.     , 74302.     ,  1593.79794,  5294.47   ,  1052.38   ,
       16666.35   ,  9012.     ])

**Find sum of every row**

In [6]:
wines.sum(axis=1)

array([ 74.5438 , 123.0548 ,  99.699  , ..., 100.48174, 105.21547,
        92.49249])

**What is its size?**

In [7]:
wines.shape

(1599, 12)

**What is the maximum residual sugar value in red wines wines?**

In [8]:
np.int_(wines[:,3])

array([1, 2, 2, ..., 2, 2, 3])

**find its maximum residual sugar value**

In [9]:
np.max(np.int_(wines[:,3]))

15

**What is the minimum residual sugar value in red wines wines?**

In [10]:
np.min(np.int_(wines[:,3]))

0

**What is the average residual sugar value in red wines wines?**

In [11]:
np.average(wines[:,3])

2.53880550343965

**What is 25 percentile residual sugar value?**

In [12]:
np.percentile(wines[:,3],25)

1.9

**What is 75 percentile residual sugar value?**

In [13]:
np.percentile(wines[:,3],75)

2.6

**Find the average of each feature value**

In [14]:
np.average(wines,axis=0)

array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311,  5.63602251])

# NumPy Array Comparisons

**Show all wines with quality > 5**

In [15]:
wines[:,-1]>5

array([False, False, False, ...,  True, False,  True])

**Show all wines with quality > 7**

In [16]:
wines[:,-1]>7

array([False, False, False, ..., False, False, False])

**check if any wines value is True for the condition quality > 7**

In [17]:
np.any(wines[:,-1],axis=0)

True

**Show first 3 rows where wine quality > 7, call it high_quality**

In [18]:
high_quality = wines[:,-1]>7

In [19]:
high_quality

array([False, False, False, ..., False, False, False])

In [20]:
# first 3 rows
high_quality[:3]

array([False, False, False])

**Show only top 3 rows and all columns of high_quality wines wines**

https://thispointer.com/python-numpy-select-elements-or-indices-by-conditions-from-numpy-array/

In [21]:
wines[high_quality][:3,]

array([[7.900e+00, 3.500e-01, 4.600e-01, 3.600e+00, 7.800e-02, 1.500e+01,
        3.700e+01, 9.973e-01, 3.350e+00, 8.600e-01, 1.280e+01, 8.000e+00],
       [1.030e+01, 3.200e-01, 4.500e-01, 6.400e+00, 7.300e-02, 5.000e+00,
        1.300e+01, 9.976e-01, 3.230e+00, 8.200e-01, 1.260e+01, 8.000e+00],
       [5.600e+00, 8.500e-01, 5.000e-02, 1.400e+00, 4.500e-02, 1.200e+01,
        8.800e+01, 9.924e-01, 3.560e+00, 8.200e-01, 1.290e+01, 8.000e+00]])

**Show wines with a lot of alcohol > 10 and high wine quality > 7**

In [22]:
alc = (wines[:,10]>10) & (wines[:,11]>7)
alc = wines[alc,:]
alc


array([[7.9000e+00, 3.5000e-01, 4.6000e-01, 3.6000e+00, 7.8000e-02,
        1.5000e+01, 3.7000e+01, 9.9730e-01, 3.3500e+00, 8.6000e-01,
        1.2800e+01, 8.0000e+00],
       [1.0300e+01, 3.2000e-01, 4.5000e-01, 6.4000e+00, 7.3000e-02,
        5.0000e+00, 1.3000e+01, 9.9760e-01, 3.2300e+00, 8.2000e-01,
        1.2600e+01, 8.0000e+00],
       [5.6000e+00, 8.5000e-01, 5.0000e-02, 1.4000e+00, 4.5000e-02,
        1.2000e+01, 8.8000e+01, 9.9240e-01, 3.5600e+00, 8.2000e-01,
        1.2900e+01, 8.0000e+00],
       [1.1300e+01, 6.2000e-01, 6.7000e-01, 5.2000e+00, 8.6000e-02,
        6.0000e+00, 1.9000e+01, 9.9880e-01, 3.2200e+00, 6.9000e-01,
        1.3400e+01, 8.0000e+00],
       [9.4000e+00, 3.0000e-01, 5.6000e-01, 2.8000e+00, 8.0000e-02,
        6.0000e+00, 1.7000e+01, 9.9640e-01, 3.1500e+00, 9.2000e-01,
        1.1700e+01, 8.0000e+00],
       [1.0700e+01, 3.5000e-01, 5.3000e-01, 2.6000e+00, 7.0000e-02,
        5.0000e+00, 1.6000e+01, 9.9720e-01, 3.1500e+00, 6.5000e-01,
        1.1000e+01,

**show only alcohol and wine quality columns**

In [23]:
alc[:,10:12]

array([[12.8,  8. ],
       [12.6,  8. ],
       [12.9,  8. ],
       [13.4,  8. ],
       [11.7,  8. ],
       [11. ,  8. ],
       [11. ,  8. ],
       [14. ,  8. ],
       [12.7,  8. ],
       [12.5,  8. ],
       [11.8,  8. ],
       [13.1,  8. ],
       [11.7,  8. ],
       [14. ,  8. ],
       [11.3,  8. ],
       [11.4,  8. ]])

# Combining NumPy Arrays

**Combine red wine and white wine wines**

In [24]:
white_wines = np.genfromtxt("winequality-white.csv", delimiter=",", skip_header=1)
white_wines

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]])

**Show size of white_wines**

In [25]:
white_wines.shape

(4898, 12)

**combine wines and white_wines wines frames using vstack and call it all_wines**

In [26]:
all_wines = np.vstack((wines,white_wines))

In [27]:
all_wines

array([[ 7.4 ,  0.7 ,  0.  , ...,  0.56,  9.4 ,  5.  ],
       [ 7.8 ,  0.88,  0.  , ...,  0.68,  9.8 ,  5.  ],
       [ 7.8 ,  0.76,  0.04, ...,  0.65,  9.8 ,  5.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]])

In [28]:
all_wines.shape

(6497, 12)

**Combine wines and white_wines wines frames using concatenate method**

In [29]:
wines2 = np.concatenate((wines,white_wines))

In [30]:
# size of wines2
wines2.shape

(6497, 12)

# Matrix Operations and Reshape

**Find Transpose of wines and print its size**

In [31]:
trans = np.transpose(wines)
trans.shape

(12, 1599)

**Convert wines wines into 1D array**

In [32]:
wines.ravel()

array([ 7.4 ,  0.7 ,  0.  , ...,  0.66, 11.  ,  6.  ])

In [33]:
# show size
wines.ravel().shape

(19188,)

**Reshape second row of wines into a 2-dimensional array with 2 rows and 6 columns**

In [34]:
wines[1,:].reshape(2,6)

array([[ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    ],
       [67.    ,  0.9968,  3.2   ,  0.68  ,  9.8   ,  5.    ]])

**Sort alcohol column Ascending Order**

In [35]:
sorted_alcohol = np.sort(wines[:,10])

In [36]:
sorted_alcohol

array([ 8.4,  8.4,  8.5, ..., 14. , 14. , 14.9])

**Make sorting to take place in-place**

In [39]:
wines[:,-2].sort()

**Show top 10 rows**

In [40]:
wines[:,-2]

array([ 8.4,  8.4,  8.5, ..., 14. , 14. , 14.9])

**Sort alcohol column Descending Order**

In [41]:
sorted_alcohol_desc=np.sort(wines[:,10])[::-1]

In [42]:
sorted_alcohol_desc

array([14.9, 14. , 14. , ...,  8.5,  8.4,  8.4])

**Will original wines be modified?. Check top 10 rows**

In [43]:
wines[:,-2]

array([ 8.4,  8.4,  8.5, ..., 14. , 14. , 14.9])