In [1]:
import numpy as np

In [2]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

numpy.zeros(shape, dtype)
returns an array of 2 rows and 2 columns with default type as float

In [8]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
arr = np.array([1,2,3])

In [14]:
arr.dtype

dtype('int32')

In [17]:
arr.astype(np.float32)

array([1., 2., 3.], dtype=float32)

implicit and explicit type casting
higher to lower we need to specify
float to int - explicit type casting

In [23]:
arr2 = np.array([1.2,3.3,1.4,1.5])

In [24]:
arr2.dtype

dtype('float64')

In [25]:
arr2.astype(np.int32)

array([1, 3, 1, 1])

In [40]:
str_arr = np.array(['2.2','3.4','3.3'],dtype=np.string_)

In [44]:
str_arr.dtype

dtype('S3')

In [42]:
str_arr.astype(np.float64)

array([2.2, 3.4, 3.3])

In [45]:
a=np.array([2,3,4],dtype=np.int16)

In [46]:
a.astype(np.float64)

array([2., 3., 4.])

In [47]:
a.dtype

dtype('int16')

1 + 15
unsigned u4 dtype -  not used 
only positve values

In [48]:
arr_uint = np.array([1,-2,3,-3],dtype='u4')

In [50]:
arr_uint.dtype

dtype('uint32')

In [51]:
arr_uint

array([         1, 4294967294,          3, 4294967293], dtype=uint32)


arithmetic ops

In [53]:
arr = np.array([[1,2,3],[4,5,6]])

In [54]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

3 types of eror
syntax error
logical error
runtime error

In [59]:
# group operation
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [60]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [61]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
arr2 = np.array([[0,-2,6],[-5.6,30.3,18.3]])

In [63]:
arr2

array([[ 0. , -2. ,  6. ],
       [-5.6, 30.3, 18.3]])

In [65]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
arr2>arr

array([[False, False,  True],
       [False,  True,  True]])

group ops is used both in arithmetic and relational ops

basic indexing and slicing

In [67]:
arr = np.arange(10)

In [68]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

indexing

In [69]:
arr[4]

4

In [70]:
arr1 = np.array([3,1.5])

In [71]:
arr1

array([3. , 1.5])

slicing

In [74]:
arr[2:8]

array([2, 3, 4, 5, 6, 7])

In [82]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
arr[5:9] = 12

In [86]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [98]:
arr[:5] = np.arange(1,6)

In [101]:
arr[:6]

array([ 1,  2,  3,  4,  5, 12])

In [100]:
a= np.arange(5)
a

array([0, 1, 2, 3, 4])

In [102]:
arr

array([ 1,  2,  3,  4,  5, 12, 12, 12, 12,  9])

In [3]:
arr = np.arange(10)